steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - project-auto-delete
      - --entry-point=delete_tbase_deployments
      - --runtime=python37
      - --source=cloud-function
      - --trigger-topic=run-tb-deleter-script
      - --timeout=540
      - --memory=512
      - --project=auto-delete-329513
      - --region=europe-west2
#      - --env-vars-file=env.prod.yaml
    env:
      - EXCLUDE_DELETE_LABEL=dont-delete
      - is_cloud_run=True
#      - dry_run=$_DRY_RUN
#      - ROOT_PROJECT=$_ROOT_PROJECT
#      - TEST_OUTSIDE_SCOPE=$_TEST_OUTSIDE_SCOPE
#      - WebHook=$_WEBHOOK
#      - EXCLUDE_EMPTY_FOLDER="Shared Services, Applications, tranquilitybase-development"


