steps:

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - project-auto-delete
      - --entry-point=delete_tbase_deployments
      - --runtime=python37
      - --source=cloud-function
      - --trigger-topic=run-tb-deleter-script
      - --timeout=540
      - --memory=512
      - --project=auto-delete-329513
      - --region=europe-west2
      - --set-env-vars=EXCLUDE_EMPTY_FOLDER="Shared Services#Applications#tranquilitybase-development"
      - --set-env-vars=EXCLUDE_DELETE_LABEL=dont-delete
      - --set-env-vars=is_cloud_run=True
      - --set-env-vars=dry_run=$_DRY_RUN
      - --set-env-vars=ROOT_PROJECT=$_ROOT_PROJECT
      - --set-env-vars=TEST_OUTSIDE_SCOPE=$_TEST_OUTSIDE_SCOPE
      - --set-env-vars=WebHook=$_WEBHOOK
